### ISSUE TITLE
Roadmap: revamp config implementation and more

### ISSUE THREAD

**Issue by aisuneko** [255doesnotexist/lintestor#29]
> 此 issue 作为 (个人) roadmap/todo 使用，也许会更新

- [x] 移除 root config 机制
- [x] distro config 添加 `enabled` 参数
- [x] 自动读取和识别 distro 目录 （通过读取distro config.toml 判断）
- [x] 引入 `--work-dir` 参数（暂定名）以替代 `--config` 参数
- [x] 自动读取和识别每个distro下的子目录（每个目录对应一个包），并汇总去重得到总package列表
- [ ] 写 unit test (really necessary?)
- [x] 写 integration test
- [x] 为已有参数添加短形式 (shorthand)
- [x] ~~实现多distro的测试脚本复用/共享~~

一些相关的远期构想：
- 重置 metadata.sh 实现，变成 package config.toml (命令也许可以通过toml里直接定义string实现?)

**Comment by aisuneko** [comment]
acf634fd2c59859ca5cf3fc31cc3e63256258526 71851fef63f363655910e72252f7a94038e61c19 completed much of the todo list

**Comment by cyjin-yl** [comment]
好快的进度TT
